### ISSUE TITLE
学习时长请教？

### ISSUE THREAD

**Issue by Chrunge** [PKUFlyingPig/CS61C-labs#1]
您好，FlyingPig：
想请教下，像61A、B、C的课程，我预计的是三个月学完，但其实我学校课程不太多，感觉自己把时间线拉的太长了。
所以想问下您的作息时间，每周学多少小时，一门课程学多久合适。

**Comment by PKUFlyingPig** [comment]
这个要看个人的兴趣和毅力了，很难一概而论。其实按部就班地学习的话个人感觉3个月是充足的，因为这三门课程的话官方的学习安排上大概也就在12周左右。另外其实倒不必太纠结于什么时候“学完”这件事，因为你的提升并不在于“学完”的那个瞬间，而在于学习的过程，再宏伟详实的计划也需要每天大量的时间投入来践行。
如果硬要算一下需要学多久的话，对于CS61A和CS61B中一些比较基础的内容（毕竟这是Berkeley大一的基础课），可以快速学习（印象中CS61A所有的内容我花了大概两周学完），对于一些毕竟重要的需要投入大量时间的内容（比如CS61B的project，CS61C的后面几个project），想急也急不得，我觉得能在两个月内学完是很吃力的（而且是在每天保持7到8小时的高强度投入下）。

**Comment by Chrunge** [comment]
看来如果想要学的快， 每天就需要更多的时间投入，那就先保证质量，以后有余力了再追求速度。
谢谢您的解惑！！！
